### ISSUE TITLE
README out of date?

### ISSUE THREAD

**Issue by davidakachaos** [rogercampos/interpret#7]
Hi, is the README out of date or something? I don't find the generators and such...

**Comment by rogercampos** [comment]
you're right, the readme is out of date, the generators are no longer there as of rails 3.1 and the engine changes, now you can run "interpret::migrations::install" to generate them. Run "rake -T" to see all the rake tasks available.

**Comment by davidakachaos** [comment]
Maybe it's an idea to update the README? I really like the project, but it's a bit difficult to start with it when the README is lacking ;-)

I got it running though, but I was looking into the layout things to intregrate it with a current backend, and that too seems to be gone?

**Comment by rogercampos** [comment]
Sure, I will accept your changes in the readme if you want to! hehe. I'm glad you like the gem, but I'm not working on it since a long time ago. In fact right now I'm investigating localepp and phraseapp, two services that does the same (they didn't exists two years ago, when I build this). Then I will decide either use one of them or work on interpret again. 

About the layout integration, yes, it's gone. The nested layouts is something not directly implemented in rails, and it had some problems. Now you can open the interpret view with "target = _blank", or even in an iframe...
